/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nsbm.universityms.view;

import java.awt.Component;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
import nsbm.university.controller.CourseController;
import nsbm.universityms.model.BatchelorCourse;
import nsbm.universityms.model.MasterCourse;



/**
 *
 * @author Dulip
 */
public class CourseDetails extends javax.swing.JInternalFrame {

    /**
     * Creates new form addcourse
     */
    
    int i; //masterpanel =2  bachelorpanel=1
    CourseController coursecontrol = new CourseController();
    public CourseDetails() {
        initComponents();
        Component [] com1 = mastera.getComponents();
        Component [] com2 = bachelora.getComponents();
        int i = 0;
        for(i=0;i<com1.length;i++)
        {
            com1[i].setEnabled(false);
        }
        
        for(i=0;i<com2.length;i++)
        {
            com2[i].setEnabled(false);
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        courseid = new javax.swing.JTextField();
        cname = new javax.swing.JTextField();
        save = new javax.swing.JButton();
        remove = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        bachelora = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        gdegree = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        sdegree = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        scredits = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        mastera = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        myears = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        mcredits = new javax.swing.JTextField();
        bachelor = new javax.swing.JButton();
        master = new javax.swing.JButton();
        heading = new javax.swing.JLabel();
        bachelorc = new javax.swing.JCheckBox();
        masterc = new javax.swing.JCheckBox();
        cancel = new javax.swing.JButton();
        update = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        courses = new javax.swing.JTable();

        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Courses");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Course id");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Course name");

        courseid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseidActionPerformed(evt);
            }
        });

        save.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        remove.setBackground(new java.awt.Color(255, 0, 0));
        remove.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        remove.setText("Remove");
        remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeActionPerformed(evt);
            }
        });

        bachelora.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bachelor degree", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("General degree ");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Special degree");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Number of years");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Number of credits per year");

        javax.swing.GroupLayout bacheloraLayout = new javax.swing.GroupLayout(bachelora);
        bachelora.setLayout(bacheloraLayout);
        bacheloraLayout.setHorizontalGroup(
            bacheloraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bacheloraLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(bacheloraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bacheloraLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(bacheloraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gdegree, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bacheloraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sdegree, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                    .addComponent(scredits))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        bacheloraLayout.setVerticalGroup(
            bacheloraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bacheloraLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(bacheloraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(bacheloraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gdegree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sdegree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(29, 29, 29)
                .addGroup(bacheloraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(scredits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 149, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 122, Short.MAX_VALUE)
        );

        mastera.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Master degree", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Number of years");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Number of credits");

        javax.swing.GroupLayout masteraLayout = new javax.swing.GroupLayout(mastera);
        mastera.setLayout(masteraLayout);
        masteraLayout.setHorizontalGroup(
            masteraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(masteraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(masteraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 48, Short.MAX_VALUE)
                .addGroup(masteraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(myears, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mcredits, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68))
        );
        masteraLayout.setVerticalGroup(
            masteraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(masteraLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(masteraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(myears, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(masteraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(mcredits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        bachelor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bachelor.setText("Bachelor");
        bachelor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bachelorActionPerformed(evt);
            }
        });

        master.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        master.setText("Master");
        master.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masterActionPerformed(evt);
            }
        });

        bachelorc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bachelorc.setText("Bachelor");
        bachelorc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bachelorcActionPerformed(evt);
            }
        });

        masterc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        masterc.setText("Master");
        masterc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mastercActionPerformed(evt);
            }
        });

        cancel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cancel.setText("Reset");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        update.setBackground(new java.awt.Color(0, 153, 255));
        update.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        courses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "", "", "", "", "", "", ""
            }
        ));
        courses.setColumnSelectionAllowed(true);
        courses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                coursesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(courses);
        courses.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        jScrollPane2.setViewportView(jScrollPane1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 752, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(bachelorc)
                        .addGap(95, 95, 95)
                        .addComponent(masterc))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(87, 87, 87)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(66, 66, 66)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(courseid, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cname, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(81, 81, 81)
                                    .addComponent(bachelora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(188, 188, 188)
                                .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(116, 116, 116)
                                .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(mastera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(53, 53, 53))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(129, 129, 129)
                                        .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(remove)))
                                .addGap(41, 41, 41)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(551, 551, 551)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(master)
                                .addGap(278, 278, 278)
                                .addComponent(bachelor))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(659, 659, 659)
                        .addComponent(heading, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(667, 667, 667)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(1165, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addComponent(heading)
                        .addGap(65, 65, 65))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bachelor)
                            .addComponent(master))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(courseid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(cname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(67, 67, 67)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(bachelorc)
                                    .addComponent(masterc))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bachelora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mastera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(131, 131, 131)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(update)
                            .addComponent(save)
                            .addComponent(cancel)
                            .addComponent(remove)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jLabel5)))
                .addGap(562, 562, 562)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        /*String id = courseid.getText();
        String name = cname.getText();
        //String fac = faculty.getText();
        String gyear;
        String gcredit; 
        String syear;
        String scredit;*/
        
        
        if(masterc.isSelected())
        {
            MasterCourse mc = new MasterCourse();
            mc.setCid(courseid.getText());
            mc.setCname(cname.getText());
            mc.setYear(myears.getText());
            mc.setCredits(mcredits.getText());
            
           
            //String sql = "insert into masterc(cid,cname,credits,year) values('"+id+"','"+name+"','"+mcredit+"','"+myear+"');";
            try {
                
                if(coursecontrol.addCourse(mc))
                {
                    JOptionPane.showMessageDialog(rootPane,"Data Entered successfully");
                    
                }
                else
                {
                    JOptionPane.showMessageDialog(rootPane,"Data Entered unsuccess");
                    System.out.println("Wrong");
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane,ex.getMessage());
                Logger.getLogger(CourseDetails.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(CourseDetails.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(rootPane,ex.getMessage());
            }
            
            
        }
        if(bachelorc.isSelected())
        {
            BatchelorCourse bc = new BatchelorCourse();
            
            bc.setCid(courseid.getText());
            bc.setCname(cname.getText());
            bc.setGyears(gdegree.getText());
            
            bc.setSyear(sdegree.getText());
            bc.setCredits(scredits.getText());
            
            
            //String sql = "insert into bachelor(cid,cname,gyears,credits,syear) values('"+id+"','"+name+"','"+gyear+"','"+scredit+"','"+syear+"');";
            try {                                              
                if(coursecontrol.addCourse(bc))
                {
                    JOptionPane.showMessageDialog(rootPane,"Data Entered successfully");
                    
                }
                else
                {
                    JOptionPane.showMessageDialog(rootPane,"Data Entered unsuccess");
                }
            } catch (SQLException ex) {
                Logger.getLogger(CourseDetails.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(rootPane,ex.getMessage());
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(CourseDetails.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(rootPane,ex.getMessage());
            }
            
        }
        
        
        
        
    }//GEN-LAST:event_saveActionPerformed

    private void clear()
    {
        JTextField [] items = {courseid,cname,gdegree,scredits,sdegree,mcredits,myears};
        int j = 0;
        for(j=0;j<items.length;j++)
        {
            items[j].setText("");
        }
    }
    private void masterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masterActionPerformed
        i = 2;
        courses.removeAll();
        heading.setText("Master courses");
        
        try {
            
            //MasterCourse mc = new MasterCourse();
            
            ResultSet result = null;
            result = coursecontrol.retrieve(2);
            if(result!=null)
            {
                courses.setModel(DbUtils.resultSetToTableModel(result));           
                try 
                {
                    result.close();
            
                } catch (SQLException ex) {
                    System.out.println(ex.getMessage());
                }
        
            }      
                   
            else 
            {
                ((DefaultTableModel)courses.getModel()).setNumRows(0);   
                System.out.println("Error");
            }
            } catch (SQLException ex) {
            Logger.getLogger(CourseDetails.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane,ex.getMessage());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CourseDetails.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane,ex.getMessage());
        }
        
        
        
        
        
        
        /*try
        {
            con.close();
        }
        catch(SQLException ex)
        {
            System.out.println("DB Error");
        }*/
        
    }//GEN-LAST:event_masterActionPerformed

    private void display(JPanel visible,JPanel invisible)
    {
        Component [] com1 = visible.getComponents();
        Component [] com2 = invisible.getComponents();
        int i = 0;
        for(i=0;i<com1.length;i++)
        {
            com1[i].setEnabled(true);
        }
        
        for(i=0;i<com2.length;i++)
        {
            com2[i].setEnabled(false);
        }
    }
    private void bachelorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bachelorActionPerformed
        i = 1;
        courses.removeAll();
        heading.setText("Bachelor courses");
        
        try {
            
            //BatchelorCourse bc = new BatchelorCourse();
            
            ResultSet result = null;
            result = coursecontrol.retrieve(1);
            if(result!=null)
            {                            
                courses.setModel(DbUtils.resultSetToTableModel(result));  
                try 
                {
                    result.close();
            
                } catch (SQLException ex) {
                    System.out.println(ex.getMessage());
                }
            }                               
            else 
            {   
                ((DefaultTableModel)courses.getModel()).setNumRows(0);   
                System.out.println("Error");
            }
            } 
        catch (SQLException ex) {
            Logger.getLogger(CourseDetails.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane,ex.getMessage());
            } catch (ClassNotFoundException ex) {
            Logger.getLogger(CourseDetails.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane,ex.getMessage());
        }
        
        

    }//GEN-LAST:event_bachelorActionPerformed

    private void bachelorcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bachelorcActionPerformed
        masterc.setSelected(false);
        display(bachelora,mastera);  
    }//GEN-LAST:event_bachelorcActionPerformed

    private void mastercActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mastercActionPerformed
        bachelorc.setSelected(false);
        display(mastera,bachelora);
        
    }//GEN-LAST:event_mastercActionPerformed

    private void courseidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_courseidActionPerformed

    private void coursesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_coursesMouseClicked
        clear();
        if(i==1)
        {
            masterc.setSelected(false);
            display(bachelora,mastera);
            
            int r = courses.getSelectedRow();
            String cid = courses.getValueAt(r,0).toString();
            String name = courses.getValueAt(r, 1).toString();
            String gyears = courses.getValueAt(r, 2).toString();
            String credity = courses.getValueAt(r, 3).toString();
            String syears = courses.getValueAt(r, 4).toString();
            
            courseid.setText(cid);
            cname.setText(name);
            scredits.setText(credity);
            gdegree.setText(gyears);
            
            sdegree.setText(syears);
        }
        else if(i==2)
        {
            
            
            bachelorc.setSelected(false);
            display(mastera,bachelora);
            int r = courses.getSelectedRow();
            String cid = courses.getValueAt(r,0).toString();
            String name = courses.getValueAt(r, 1).toString();
            String credits = courses.getValueAt(r, 2).toString();
            String years = courses.getValueAt(r, 3).toString();
            courseid.setText(cid);
            cname.setText(name);
            mcredits.setText(credits);
            myears.setText(years);
        }
        else
        {
        }
        
        
        
        
        
    }//GEN-LAST:event_coursesMouseClicked

    private void removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeActionPerformed
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog (null, "Are you sure you want to remove?","Warning",dialogButton);
        if(JOptionPane.YES_NO_OPTION != dialogResult)
        {
            return;
        }

        
        
        try {
            
            if(i==2)
            {
               
                MasterCourse mc = new MasterCourse();
                mc.setCid(courseid.getText());
                if(coursecontrol.removeCourse(mc))
                {
                    JOptionPane.showMessageDialog(rootPane,"Data Removed successfully");
                }
                else 
                {
                    JOptionPane.showMessageDialog(rootPane,"Data Removed unsuccess");
                }
            }
            if(i==1)
            {
                BatchelorCourse bc = new BatchelorCourse();
                bc.setCid(courseid.getText());
                if(coursecontrol.removeCourse(bc))
                {
                    JOptionPane.showMessageDialog(rootPane,"Data Removed successfully");
                }
                else 
                {
                    JOptionPane.showMessageDialog(rootPane,"Data Removed unsuccess");
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(CourseDetails.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane,ex.getMessage());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CourseDetails.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane,ex.getMessage());
        }
        
        
        
    }//GEN-LAST:event_removeActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        clear();
        courses.clearSelection();
    }//GEN-LAST:event_cancelActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
       
        try {
            
            
            if(i==2)
            {
                MasterCourse mc = new MasterCourse();
                mc.setCid(courseid.getText());
                mc.setCname(cname.getText());
                mc.setYear(myears.getText());
                mc.setCredits(mcredits.getText());
                
            
                if(coursecontrol.updateCourse(mc))
                {
                    JOptionPane.showMessageDialog(rootPane,"Data Updated successfully");
                }
                else
                {
                    JOptionPane.showMessageDialog(rootPane,"Data Updated unsuccess");
                }
            
            
            }
            if(i==1)
            {
                BatchelorCourse bc = new BatchelorCourse();
                bc.setCid(courseid.getText());
                bc.setCname(cname.getText());
                bc.setGyears(gdegree.getText());
                bc.setSyear(sdegree.getText());
                bc.setCredits(scredits.getText());
                
            
            
                if(coursecontrol.updateCourse(bc))
                {
                    JOptionPane.showMessageDialog(rootPane,"Data Updated successfully");
                }
                else
                {
                    JOptionPane.showMessageDialog(rootPane,"Data Updated unsuccess");
                }
            
            }
            }
        catch (SQLException ex) {
                Logger.getLogger(CourseDetails.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(rootPane,ex.getMessage());
            } catch (ClassNotFoundException ex) {
            Logger.getLogger(CourseDetails.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane,ex.getMessage());
        }
        
        
        
    }//GEN-LAST:event_updateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bachelor;
    private javax.swing.JPanel bachelora;
    private javax.swing.JCheckBox bachelorc;
    private javax.swing.JButton cancel;
    private javax.swing.JTextField cname;
    private javax.swing.JTextField courseid;
    private javax.swing.JTable courses;
    private javax.swing.JTextField gdegree;
    private javax.swing.JLabel heading;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton master;
    private javax.swing.JPanel mastera;
    private javax.swing.JCheckBox masterc;
    private javax.swing.JTextField mcredits;
    private javax.swing.JTextField myears;
    private javax.swing.JButton remove;
    private javax.swing.JButton save;
    private javax.swing.JTextField scredits;
    private javax.swing.JTextField sdegree;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
